### ISSUE TITLE
[1.17]サーバ起動時にエラーがでてプラグインが読み込まれない

### ISSUE THREAD

**Issue by graycat27** [graycat27/AirportTrafficController#30]
以下、コンソールに出力されたログ
```
[11:26:07] [Server thread/ERROR]: Could not load 'plugins\AirportTrafficController-0.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:180) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:384) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 2, column 10:
    version: @version@
             ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:439) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:633) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:309) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:300) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:259) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:175) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	... 6 more
[11:26:09] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

**Comment by graycat27** [comment]
#28 (#29) 時点での修正漏れ
