### ISSUE TITLE
新規に周波数を割り当てたときに内部エラーが発生する

### ISSUE THREAD

**Issue by graycat27** [graycat27/AirportTrafficController#31]
独自にビルドした1.17LunaChatと組み合わせての試行
CTL周波数を割り当てるコマンドを実行した際に
Internal Error として処理ABEND

以下、コンソールログ
```
[11:40:14] [Server thread/INFO]: gray27 issued server command: /atc manage add airport Sample
[11:40:14] [Server thread/INFO]: update event handled
[11:40:29] [Server thread/INFO]: gray27 issued server command: /atc manage mod airport Sample CTL_freq 272.7
[11:40:29] [Server thread/INFO]: §f[§f§fatc_freq_272_7§f]§7[ATC]admin さんがチャンネルに参加しました。
[11:40:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'atc' in plugin AirportTraficController v0.1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1943) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1782) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1763) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1100) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.ucchyocean.lc3.member.ChannelMember.getName()" because "player" is null
	at com.github.ucchyocean.lc3.channel.Channel.addMember(Channel.java:510) ~[?:?]
	at com.github.graycat27.atc.defines.atc.LunaChatChannelFrequency.setChannelMember(LunaChatChannelFrequency.java:86) ~[?:?]
	at com.github.graycat27.atc.defines.atc.LunaChatChannelFrequency.createLcChannelIfNonExists(LunaChatChannelFrequency.java:56) ~[?:?]
	at com.github.graycat27.atc.defines.atc.LunaChatChannelFrequency.<init>(LunaChatChannelFrequency.java:35) ~[?:?]
	at com.github.graycat27.atc.handler.command.action.CommandAirport.setupNewFrequency(CommandAirport.java:96) ~[?:?]
	at com.github.graycat27.atc.handler.command.action.CommandAirport.setControlFreqForAirport(CommandAirport.java:88) ~[?:?]
	at com.github.graycat27.atc.handler.command.action.CommandAirport.mod(CommandAirport.java:59) ~[?:?]
	at com.github.graycat27.atc.handler.command.AtcCommandHandler.onCommand(AtcCommandHandler.java:125) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.jar:3118-Spigot-66f9d3c-27835bd]
	... 19 more
```
この時点で、LunaChatのチャンネルは作成されているが、
フォーマットの適用等ができていなかった

**Comment by graycat27** [comment]
https://github.com/graycat27/AirportTrafficController/blob/main/src/main/java/com/github/graycat27/atc/components/FrequencyUtil.java#L36
新規に作成された時点で、このデータ検索で抽出できずnullが返っているとみられる

**Comment by graycat27** [comment]
データソースに対して、周波数を指定する情報の更新処理がされておらず、
```
[15:26:49] [Server thread/INFO]: gray27 issued server command: /atc manage add airport Sample
[15:26:49] [Server thread/INFO]: update event handled
[15:27:01] [Server thread/INFO]: gray27 issued server command: /atc manage mod airport Sample CTL_freq 272.7
[15:27:01] [Server thread/INFO]: §f[§f§fatc_freq_272_7§f]§7[ATC]admin さんがチャンネルに参加しました。
[15:27:01] [Server thread/INFO]: Name: Sample
[15:27:01] [Server thread/INFO]: AtcName: null
[15:27:01] [Server thread/INFO]: Tower: unset
[15:27:01] [Server thread/INFO]: ControlArea: [AtcControl: {Control: TWR, Frequency: unset, Area: unset},AtcControl: {Control: CTL, Frequency: unset, Area: unset}]
[15:27:01] [Server thread/INFO]: Runways: unset
[15:27:01] [Server thread/INFO]: Taxiways: unset
[15:27:01] [Server thread/INFO]: Spots: unset
[15:27:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'atc' in plugin AirportTraficController v0.1.0
```
unsetなので抽出できない
